call code --install-extension 13xforever.language-x86-64-assembly
call code --install-extension cpmcgrath.codealignment-vscode
call code --install-extension DotJoshJohnson.xml
call code --install-extension Equinusocio.vsc-material-theme
call code --install-extension himanoa.Python-autopep8
call code --install-extension James-Yu.latex-workshop
call code --install-extension jkjustjoshing.vscode-text-pastry
call code --install-extension johnstoncode.svn-scm
call code --install-extension kosz78.nim
call code --install-extension lextudio.restructuredtext
call code --install-extension ms-python.python
call code --install-extension ms-vscode.cpptools
call code --install-extension mshr-h.veriloghdl
call code --install-extension samrapdev.outrun
call code --install-extension shuworks.vscode-table-formatter
call code --install-extension sleutho.tcl
call code --install-extension Stephanvs.dot
call code --install-extension stkb.rewrap
call code --install-extension streetsidesoftware.code-spell-checker
call code --install-extension tomphilbin.gruvbox-themes
call code --install-extension trixnz.vscode-lua
call code --install-extension wayou.vscode-todo-highlight
call code --install-extension xaver.clang-format
