code --force --install-extension 13xforever.language-x86-64-assembly
code --force --install-extension adbayb.vscode-theme-honeymoon
code --force --install-extension arcsine.chronicler
code --force --install-extension arcticicestudio.nord-visual-studio-code
code --force --install-extension ashrafhadden.dracula-dot-min
code --force --install-extension ban.troff
code --force --install-extension barjo.anirak
code --force --install-extension be5invis.theme-verdandi
code --force --install-extension bungcip.better-toml
code --force --install-extension chmac.insert-random-hashtag
code --force --install-extension christianbrassat.minimal-fedu-ext
code --force --install-extension cocopon.iceberg-theme
code --force --install-extension cpmcgrath.codealignment-vscode
code --force --install-extension cr-jr.chronotype-vscode-themes
code --force --install-extension csilva2810.rose-pine-next
code --force --install-extension damienstanton.nil
code --force --install-extension daniel-lvovsky.mintdark-theme
code --force --install-extension daniel-lvovsky.mintlight-theme
code --force --install-extension Dj.minimal-fedu
code --force --install-extension DotJoshJohnson.xml
code --force --install-extension dracula-theme.theme-dracula
code --force --install-extension eamodio.gitlens
code --force --install-extension Equinusocio.vsc-community-material-theme
code --force --install-extension Equinusocio.vsc-material-theme
code --force --install-extension equinusocio.vsc-material-theme-icons
code --force --install-extension esbenp.prettier-vscode
code --force --install-extension Gruntfuggly.todo-tree
code --force --install-extension hawkeyegold.bonsai
code --force --install-extension himanoa.Python-autopep8
code --force --install-extension James-Yu.latex-workshop
code --force --install-extension jkjustjoshing.vscode-text-pastry
code --force --install-extension joaomoreno.github-sharp-theme
code --force --install-extension johnstoncode.svn-scm
code --force --install-extension jolaleye.horizon-theme-vscode
code --force --install-extension julialang.language-julia
code --force --install-extension konstantin.plain
code --force --install-extension kosz78.nim
code --force --install-extension lextudio.restructuredtext
code --force --install-extension marcusolsson.enough-visual-studio-code
code --force --install-extension ms-azuretools.vscode-docker
code --force --install-extension ms-python.python
code --force --install-extension ms-python.vscode-pylance
code --force --install-extension ms-toolsai.jupyter
code --force --install-extension ms-vscode-remote.remote-ssh
code --force --install-extension ms-vscode-remote.remote-ssh-edit
code --force --install-extension ms-vscode-remote.remote-ssh-explorer
code --force --install-extension ms-vscode-remote.remote-wsl
code --force --install-extension ms-vscode.cmake-tools
code --force --install-extension ms-vscode.cpptools
code --force --install-extension mshr-h.veriloghdl
code --force --install-extension mullakhmetov.shale
code --force --install-extension mvllow.rose-pine
code --force --install-extension octref.lsp-inspector-webview
code --force --install-extension pureux.grueling-hare
code --force --install-extension pyxel.flare-theme
code --force --install-extension pyxel.runic-theme
code --force --install-extension rust-lang.rust
code --force --install-extension sainnhe.gruvbox-material
code --force --install-extension samrapdev.outrun
code --force --install-extension Shirayuki.verdandi-alter-customized
code --force --install-extension shuworks.vscode-table-formatter
code --force --install-extension sleutho.tcl
code --force --install-extension slevesque.vscode-hexdump
code --force --install-extension Stephanvs.dot
code --force --install-extension sthenic.vls-vscode
code --force --install-extension stkb.rewrap
code --force --install-extension streetsidesoftware.code-spell-checker
code --force --install-extension thomaspink.theme-github
code --force --install-extension tomphilbin.gruvbox-themes
code --force --install-extension trixnz.vscode-lua
code --force --install-extension twxs.cmake
code --force --install-extension vladimir-genkin.artemis
code --force --install-extension wayou.vscode-todo-highlight
code --force --install-extension webfreak.debug
code --force --install-extension xaver.clang-format
code --force --install-extension ZixuanWang.linkerscript
