call code --force --install-extension 13xforever.language-x86-64-assembly
call code --force --install-extension adbayb.vscode-theme-honeymoon
call code --force --install-extension arcsine.chronicler
call code --force --install-extension arcticicestudio.nord-visual-studio-code
call code --force --install-extension ashrafhadden.dracula-dot-min
call code --force --install-extension ban.troff
call code --force --install-extension barjo.anirak
call code --force --install-extension be5invis.theme-verdandi
call code --force --install-extension bungcip.better-toml
call code --force --install-extension chmac.insert-random-hashtag
call code --force --install-extension christianbrassat.minimal-fedu-ext
call code --force --install-extension cocopon.iceberg-theme
call code --force --install-extension cpmcgrath.codealignment-vscode
call code --force --install-extension cr-jr.chronotype-vscode-themes
call code --force --install-extension csilva2810.rose-pine-next
call code --force --install-extension damienstanton.nil
call code --force --install-extension daniel-lvovsky.mintdark-theme
call code --force --install-extension daniel-lvovsky.mintlight-theme
call code --force --install-extension Dj.minimal-fedu
call code --force --install-extension DotJoshJohnson.xml
call code --force --install-extension dracula-theme.theme-dracula
call code --force --install-extension eamodio.gitlens
call code --force --install-extension Equinusocio.vsc-community-material-theme
call code --force --install-extension Equinusocio.vsc-material-theme
call code --force --install-extension equinusocio.vsc-material-theme-icons
call code --force --install-extension esbenp.prettier-vscode
call code --force --install-extension Gruntfuggly.todo-tree
call code --force --install-extension hawkeyegold.bonsai
call code --force --install-extension himanoa.Python-autopep8
call code --force --install-extension James-Yu.latex-workshop
call code --force --install-extension jkjustjoshing.vscode-text-pastry
call code --force --install-extension joaomoreno.github-sharp-theme
call code --force --install-extension johnstoncode.svn-scm
call code --force --install-extension jolaleye.horizon-theme-vscode
call code --force --install-extension julialang.language-julia
call code --force --install-extension konstantin.plain
call code --force --install-extension kosz78.nim
call code --force --install-extension lextudio.restructuredtext
call code --force --install-extension marcusolsson.enough-visual-studio-code
call code --force --install-extension ms-azuretools.vscode-docker
call code --force --install-extension ms-python.python
call code --force --install-extension ms-python.vscode-pylance
call code --force --install-extension ms-toolsai.jupyter
call code --force --install-extension ms-vscode-remote.remote-ssh
call code --force --install-extension ms-vscode-remote.remote-ssh-edit
call code --force --install-extension ms-vscode-remote.remote-ssh-explorer
call code --force --install-extension ms-vscode-remote.remote-wsl
call code --force --install-extension ms-vscode.cmake-tools
call code --force --install-extension ms-vscode.cpptools
call code --force --install-extension mshr-h.veriloghdl
call code --force --install-extension mullakhmetov.shale
call code --force --install-extension mvllow.rose-pine
call code --force --install-extension octref.lsp-inspector-webview
call code --force --install-extension pureux.grueling-hare
call code --force --install-extension pyxel.flare-theme
call code --force --install-extension pyxel.runic-theme
call code --force --install-extension rust-lang.rust
call code --force --install-extension sainnhe.gruvbox-material
call code --force --install-extension samrapdev.outrun
call code --force --install-extension Shirayuki.verdandi-alter-customized
call code --force --install-extension shuworks.vscode-table-formatter
call code --force --install-extension sleutho.tcl
call code --force --install-extension slevesque.vscode-hexdump
call code --force --install-extension Stephanvs.dot
call code --force --install-extension sthenic.vls-vscode
call code --force --install-extension stkb.rewrap
call code --force --install-extension streetsidesoftware.code-spell-checker
call code --force --install-extension thomaspink.theme-github
call code --force --install-extension tomphilbin.gruvbox-themes
call code --force --install-extension trixnz.vscode-lua
call code --force --install-extension twxs.cmake
call code --force --install-extension vladimir-genkin.artemis
call code --force --install-extension wayou.vscode-todo-highlight
call code --force --install-extension webfreak.debug
call code --force --install-extension xaver.clang-format
call code --force --install-extension ZixuanWang.linkerscript
