alias ll='ls -lhGgF --group-directories-first --color=auto'

alias set-nighttime='redshift -O 3500'
alias set-daytime='redshift -x'

# Git
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log'
alias gp='git push'
alias gs='git status'
alias gds='git diff --staged'
alias gls='git log --numstat'
alias glo='git log --oneline'
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"


# Paths
alias gitdir='cd ~/Documents/git'
alias codedir='cd ~/Documents/code'
alias tg='gitdir && cd technogram'

# Visual studio code (needed due to bug https://github.com/Microsoft/vscode/issues/41513)
alias code='code --disable-gpu'
