alias ll='ls -lhGgF --group-directories-first --color=auto'

alias set-nighttime='redshift -O 3500'
alias set-daytime='redshift -x'

# Git
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log'
alias gp='git push'
alias gstat='git status'
alias gds='git diff --staged'
alias gls='git log --numstat'

# Paths
alias gitdir='cd ~/Documents/git'
alias tg='gitdir && cd technogram'
